# Generated by Django 5.2.3 on 2025-09-17 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artickles',
            new_name='Articles',
        ),
    ]
