# Generated by Django 5.2.3 on 2025-09-17 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_artickles_articles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='articles',
            new_name='title',
        ),
    ]
