# Generated by Django 5.2.3 on 2025-09-21 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_articles_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='author',
        ),
    ]
