# Generated by Django 5.2.2 on 2025-10-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_mediapost'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Likes'),
        ),
    ]
