# Generated by Django 5.2.6 on 2025-09-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='promt_name')),
                ('text', models.TextField(max_length=250, verbose_name='text')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='date')),
            ],
            options={
                'verbose_name': 'Promt',
                'verbose_name_plural': 'Promts',
            },
        ),
    ]
